### ISSUE TITLE
No dependency on kernel-devel package for dkms-nvidia

### ISSUE THREAD

**Issue by AlexanderVL** [negativo17/dkms-nvidia#1]
Just a while ago I did a fresh installation of Fedora 24. Then I followed the instructions on http://negativo17.org/nvidia-driver/ and did a `dnf install nvidia-driver dkms-nvidia` and restarted. I'm not sure if `dnf update` pulled in a new kernel version and I installed the nvidia driver in the same session, but it's possible.

When I rebooted both the old kernel and new kernel (4.5 and 4.6) couldn’t start GNOME and hung at "Switching root". I didn't have much of a clue, but I after some searching on the net I figured out that the DKMS module was not built. I booted again with runlevel 3 and tried to execute the `dkms install -k <kernel_version> -m nvidia -v <version> --verbose` command listed on the nvidia driver's page, but that didn't work because kernel headers weren't available for each of my kernels.

I decided to undo the installation of the nvidia drivers through the `dnf history undo` command and booted into GNOME again with nouveau. Then I installed the kernel-devel package and after that executed `dnf install nvidia-driver dkms-nvidia` again. This time the dkms module was built because the process took much longer. I rebooted and am know typing this from my box with the proprietary nvidia driver enabled.

So shouldn't the dkms-nvidia package (or the dkms package itself) have a dependency on the kernel-devel package? I had to install it manually. A new Fedora version is always a guarantee for adventure ;) Proud to have solved this myself. Of course let me use this opportunity to thank you, Simone Caronni, for helping out so many Fedora users with your nvidia, Steam and other packages.

**Comment by scaronni** [comment]
Hello,

the `dkms-nvidia` package has a dependency on `dkms`, which in turn asks for kernel-devel; so the dependencies are correct:

```
$ rpm -q --requires dkms-nvidia | grep dkms
dkms
$ rpm -q --requires dkms | grep kernel
kernel-devel
```

in the instructions I wrote that you need to explicitly install `kernel-devel` because it's a know problem with dnf/yum, the bug is open since forever:

https://bugzilla.redhat.com/show_bug.cgi?id=1228897

**Comment by AlexanderVL** [comment]
Ouch :O I promise I'll read the instructions more carefully next time ;)

**Comment by AlexanderVL** [comment]
Actually, the reason I missed that in the instructions is because the instructions don't seem to be very clear. You write only the following about the kernel-devel package:

Make sure you have the RPMFusion repository enabled if you plan to use AKMOD kernel modules:
yum -y install nvidia-driver akmod-nvidia kernel-devel
Requirement on kernel-devel is required as otherwise the package kernel-debug-devel is pulled in automatically in place of the normal non-debug package.

But I only installed the dkms-nvidia package as instructed in your example and not the akmod-nvidia package. That's why I thought the instructions didn't apply to my situation. Maybe you could clarify the instructions at this point? I.e., that the kernel-devel package is also required if dkms-nvidia is used?

**Comment by scaronni** [comment]
Oh, thanks for pointing it out, I will make the appropriate change in the web page.

**Comment by scaronni** [comment]
Done.
