### ISSUE TITLE
Blank Screen issue

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [negativo17/dkms-nvidia#2]
Hi,

I had terrible issues with getting an Optimus laptop (Alienware R3 15) to work with this driver set.  

When booting, it would run through the standard init scripts, run X and the screen would simply be blank or stuck on whatever was last on the screen.  The system was otherwise working fine, just no display available.

After considerable debugging I found the issue.  As part of your 'it just works' approach to the driver (and thank you, it really is awesome), you insert 'nomodeset' into the kernel parameters at boot  time.  This was the root cause of my issue and its removal completely solved my problems.

I'm not sure if this would be repeatable for others or if I'm in a small minority but finding the cause was very painful.  It might be worth calling out on your driver page to help others.

I'm running a clean install of F25 with kernel 4.9.6-200, x86_64.

Please let me know if you need more detail.

**Comment by scaronni** [comment]
Hi, this actually should already be fine in one of the latest builds:

https://github.com/negativo17/nvidia-driver/blob/fedora-25/nvidia-driver.spec#L21-L22

https://github.com/negativo17/nvidia-driver/blob/fedora-25/nvidia-driver.spec#L336-L340

Please let me know if it is fixed.

**Comment by scaronni** [comment]
Also please see this:

http://negativo17.org/complex-setup-with-nvidia-optimus-nouveau-prime-on-fedora-20/

This was the status until the recent development by Hans De Geode.
