### ISSUE TITLE
Doesn't work with kernel 4.11.0

### ISSUE THREAD

**Issue by welbers** [negativo17/dkms-nvidia#3]
Output of: dkms install nvidia/375.66 -k 4.11.0-1.el7.elrepo.x86_64
======================================================

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
'make' -j2 module SYSSRC=/lib/modules/4.11.0-1.el7.elrepo.x86_64/build IGNORE_XEN_PRESENCE=1 IGNORE_PREEMPT_RT_PRESENCE=1............(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.11.0-1.el7.elrepo.x86_64 (x86_64)
Consult /var/lib/dkms/nvidia/375.66/build/make.log for more information.

Tail of the make.log Logfile:
=======================
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-connector.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-gem.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-fb.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-modeset.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-mmap.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-fence.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nvidia-drm-linux.o
CC [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm/nv-pci-table.o
ld -r -o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-interface.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-frontend.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-instance.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-acpi.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-chrdev.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-cray.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-dma.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-gvi.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-i2c.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-mempool.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-mmap.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-p2p.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-pat.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-procfs.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-usermap.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-vm.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-vtophys.o /var/lib/dkms/nvidia/375.66/build/nvidia/os-interface.o /var/lib/dkms/nvidia/375.66/build/nvidia/os-mlock.o /var/lib/dkms/nvidia/375.66/build/nvidia/os-pci.o /var/lib/dkms/nvidia/375.66/build/nvidia/os-registry.o /var/lib/dkms/nvidia/375.66/build/nvidia/os-usermap.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-modeset-interface.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-pci-table.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-kthread-q.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv-kthread-q-selftest.o /var/lib/dkms/nvidia/375.66/build/nvidia/nv_uvm_interface.o /var/lib/dkms/nvidia/375.66/build/nvidia/ebridge_linux.o /var/lib/dkms/nvidia/375.66/build/nvidia/ibmnpu_linux.o /var/lib/dkms/nvidia/375.66/build/nvidia/nvlink_linux.o /var/lib/dkms/nvidia/375.66/build/nvidia/nvlink_pci.o
ld -r -o /var/lib/dkms/nvidia/375.66/build/nvidia-modeset/nv-modeset-interface.o /var/lib/dkms/nvidia/375.66/build/nvidia-modeset/nvidia-modeset-linux.o
LD [M] /var/lib/dkms/nvidia/375.66/build/nvidia.o
LD [M] /var/lib/dkms/nvidia/375.66/build/nvidia-uvm.o
LD [M] /var/lib/dkms/nvidia/375.66/build/nvidia-modeset.o
LD [M] /var/lib/dkms/nvidia/375.66/build/nvidia-drm.o
Building modules, stage 2.
MODPOST 4 modules
FATAL: modpost: GPL-incompatible module nvidia-drm.ko uses GPL-only symbol 'refcount_inc'
make[2]: *** [__modpost] Fehler 1
make[1]: *** [modules] Fehler 2
make[1]: Leaving directory `/usr/src/kernels/4.11.0-1.el7.elrepo.x86_64'
make: *** [modules] Fehler 2

**Comment by scaronni** [comment]
That was fast. :)

New update coming in a minute. Patch not needed after next 4.11.1 kernel release.
