### ISSUE TITLE
Fedora 27 kernel.x86_64 4.13.2-300 nvidia/384.69 build failure

### ISSUE THREAD

**Issue by tla2k12** [negativo17/dkms-nvidia#4]
Hi,

  Noticed that the dkms kernel module build failed today with Fedora 27 kernel.x86_64 4.13.2-300.

> $ cat /var/lib/dkms/nvidia/384.69/build/make.log
> DKMS make.log for nvidia-384.69 for kernel 4.13.2-300.fc27.x86_64 (x86_64)
> Mon 18 Sep 09:34:53 BST 2017
> make "CC=cc"  KBUILD_VERBOSE= -C /lib/modules/4.13.2-300.fc27.x86_64/build M=/var/lib/dkms/nvidia/384.69/build ARCH=x86_64 NV_KERNEL_SOURCES=/lib/modules/4.13.2-300.fc27.x86_64/build NV_KERNEL_OUTPUT=/lib/modules/4.13.2-300.fc27.x86_64/build NV_KERNEL_MODULES="nvidia nvidia-uvm nvidia-modeset nvidia-drm" INSTALL_MOD_DIR=kernel/drivers/video modules
> make[1]: Entering directory '/usr/src/kernels/4.13.2-300.fc27.x86_64'
>   SYMLINK /var/lib/dkms/nvidia/384.69/build/nvidia/nv-kernel.o
>   SYMLINK /var/lib/dkms/nvidia/384.69/build/nvidia-modeset/nv-modeset-kernel.o
>  CONFTEST: INIT_WORK
>  CONFTEST: remap_pfn_range
>  CONFTEST: hash__remap_4k_pfn
>  CONFTEST: follow_pfn
>  CONFTEST: vmap
>  CONFTEST: set_pages_uc
>  CONFTEST: set_memory_uc
>  CONFTEST: set_memory_array_uc
>  CONFTEST: change_page_attr
>  CONFTEST: pci_get_class
>  CONFTEST: pci_choose_state
>  CONFTEST: vm_insert_page
>  CONFTEST: acpi_device_id
>  CONFTEST: acquire_console_sem
>  CONFTEST: console_lock
>  CONFTEST: kmem_cache_create
>  CONFTEST: on_each_cpu
>  CONFTEST: smp_call_function
>  CONFTEST: acpi_evaluate_integer
>  CONFTEST: ioremap_cache
>  CONFTEST: ioremap_wc
>  CONFTEST: acpi_walk_namespace
>  CONFTEST: pci_domain_nr
>  CONFTEST: pci_dma_mapping_error
>  CONFTEST: sg_alloc_table
>  CONFTEST: sg_init_table
>  CONFTEST: pci_get_domain_bus_and_slot
>  CONFTEST: get_num_physpages
>  CONFTEST: efi_enabled
>  CONFTEST: proc_create_data
>  CONFTEST: pde_data
>  CONFTEST: proc_remove
>  CONFTEST: pm_vt_switch_required
>  CONFTEST: xen_ioemu_inject_msi
>  CONFTEST: phys_to_dma
>  CONFTEST: get_dma_ops
>  CONFTEST: write_cr4
>  CONFTEST: of_get_property
>  CONFTEST: of_find_node_by_phandle
>  CONFTEST: of_node_to_nid
>  CONFTEST: pnv_pci_get_npu_dev
>  CONFTEST: for_each_online_node
>  CONFTEST: node_end_pfn
>  CONFTEST: pci_bus_address
>  CONFTEST: pci_stop_and_remove_bus_device
>  CONFTEST: pci_remove_bus_device
>  CONFTEST: request_threaded_irq
>  CONFTEST: register_cpu_notifier
>  CONFTEST: cpuhp_setup_state
>  CONFTEST: remap_page_range
>  CONFTEST: address_space_init_once
>  CONFTEST: kbasename
>  CONFTEST: fatal_signal_pending
>  CONFTEST: list_cut_position
>  CONFTEST: vzalloc
>  CONFTEST: wait_on_bit_lock_argument_count
>  CONFTEST: bitmap_clear
>  CONFTEST: usleep_range
>  CONFTEST: radix_tree_empty
>  CONFTEST: drm_dev_unref
>  CONFTEST: drm_reinit_primary_mode_group
>  CONFTEST: drm_atomic_set_mode_for_crtc
>  CONFTEST: drm_atomic_clean_old_fb
>  CONFTEST: get_user_pages_remote
>  CONFTEST: drm_gem_object_lookup
>  CONFTEST: drm_atomic_state_free
>  CONFTEST: drm_driver_has_gem_prime_res_obj
>  CONFTEST: is_export_symbol_gpl_of_node_to_nid
>  CONFTEST: i2c_adapter
>  CONFTEST: pm_message_t
>  CONFTEST: irq_handler_t
>  CONFTEST: acpi_device_ops
>  CONFTEST: acpi_op_remove
>  CONFTEST: outer_flush_all
>  CONFTEST: proc_dir_entry
>  CONFTEST: scatterlist
>  CONFTEST: sg_table
>  CONFTEST: file_operations
>  CONFTEST: vm_operations_struct
>  CONFTEST: atomic_long_type
>  CONFTEST: pci_save_state
>  CONFTEST: file_inode
>  CONFTEST: task_struct
>  CONFTEST: kuid_t
>  CONFTEST: dma_ops
>  CONFTEST: dma_map_ops
>  CONFTEST: noncoherent_swiotlb_dma_ops
>  CONFTEST: vm_fault_present
>  CONFTEST: vm_fault_has_address
>  CONFTEST: fault_flags
>  CONFTEST: atomic64_type
>  CONFTEST: address_space
>  CONFTEST: backing_dev_info
>  CONFTEST: kernel_write
>  CONFTEST: strnstr
>  CONFTEST: iterate_dir
>  CONFTEST: kstrtoull
>  CONFTEST: mm_context_t
>  CONFTEST: vm_ops_fault_removed_vma_arg
>  CONFTEST: pnv_npu2_init_context
>  CONFTEST: drm_bus_present
>  CONFTEST: drm_bus_has_bus_type
>  CONFTEST: drm_bus_has_get_irq
>  CONFTEST: drm_bus_has_get_name
>  CONFTEST: drm_driver_has_legacy_dev_list
>  CONFTEST: drm_driver_has_set_busid
>  CONFTEST: drm_crtc_state_has_connectors_changed
>  CONFTEST: drm_init_functions_have_name_arg
>  CONFTEST: drm_mode_connector_list_update_has_merge_type_bits_arg
>  CONFTEST: drm_helper_mode_fill_fb_struct
>  CONFTEST: drm_master_drop_has_from_release_arg
>  CONFTEST: drm_mode_config_funcs_has_atomic_state_alloc
>  CONFTEST: drm_driver_unload_has_int_return_type
>  CONFTEST: dom0_kernel_present
>  CONFTEST: nvidia_vgpu_kvm_build
>  CONFTEST: nvidia_grid_build
>  CONFTEST: drm_available
>  CONFTEST: drm_atomic_available
>  CONFTEST: drm_atomic_modeset_nonblocking_commit_available
>  CONFTEST: is_export_symbol_gpl_refcount_inc
>  CONFTEST: is_export_symbol_gpl_refcount_dec_and_test
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-frontend.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-instance.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-acpi.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-chrdev.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-cray.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-dma.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-gvi.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-i2c.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-mempool.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-mmap.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-p2p.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-pat.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-procfs.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-usermap.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-vm.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-vtophys.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/os-interface.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/os-mlock.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/os-pci.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/os-registry.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/os-usermap.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-modeset-interface.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-pci-table.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-kthread-q.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-kthread-q-selftest.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv-memdbg.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nv_uvm_interface.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia/nvlink_linux.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_volta_host.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_volta.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_volta_fault_buffer.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_volta_access_counter_buffer.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_ats_numa.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu_non_replayable_faults.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu_access_counters.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm_utils.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm_common.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm_linux.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/nvstatus.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/nv-kthread-q.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/nv-kthread-q-selftest.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_tools.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_global.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu_isr.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_procfs.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_va_space.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu_semaphore.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_mem.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_rm_mem.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_channel.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_lock.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_hal.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_range_tree.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_range_allocator.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_va_range.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_va_block.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_range_group.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu_replayable_faults.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_events.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_module.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_mmu.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pte_batch.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_tlb_batch.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_push.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pushbuffer.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_thread_context.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_tracker.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_kepler.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_kepler_ce.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_kepler_host.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_kepler_mmu.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_maxwell.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_maxwell_host.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pascal.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pascal_ce.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pascal_host.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pascal_mmu.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pascal_fault_buffer.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_policy.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_utils.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_kvmalloc.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pmm_gpu.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_migrate.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_map_external.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_user_channel.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_hmm.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_heuristics.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_thrashing.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_prefetch.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_test_rng.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_range_tree_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_range_allocator_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_gpu_semaphore_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_mem_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_rm_mem_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_page_tree_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_tracker_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_push_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_channel_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_ce_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_lock_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_utils_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_kvmalloc_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_pmm_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_events_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_perf_module_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_get_rm_ptes_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_fault_buffer_flush_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_mmu_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_peer_identity_mappings_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_va_block_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm/uvm8_range_group_tree_test.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-modeset/nvidia-modeset-linux.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-drv.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-utils.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-crtc.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-encoder.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-connector.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-gem.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-fb.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-modeset.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-prime-fence.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-linux.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nvidia-drm-helper.o
>   CC [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm/nv-pci-table.o
> ld -r -o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-interface.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-frontend.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-instance.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-acpi.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-chrdev.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-cray.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-dma.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-gvi.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-i2c.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-mempool.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-mmap.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-p2p.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-pat.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-procfs.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-usermap.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-vm.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-vtophys.o /var/lib/dkms/nvidia/384.69/build/nvidia/os-interface.o /var/lib/dkms/nvidia/384.69/build/nvidia/os-mlock.o /var/lib/dkms/nvidia/384.69/build/nvidia/os-pci.o /var/lib/dkms/nvidia/384.69/build/nvidia/os-registry.o /var/lib/dkms/nvidia/384.69/build/nvidia/os-usermap.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-modeset-interface.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-pci-table.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-kthread-q.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-kthread-q-selftest.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv-memdbg.o /var/lib/dkms/nvidia/384.69/build/nvidia/nv_uvm_interface.o /var/lib/dkms/nvidia/384.69/build/nvidia/nvlink_linux.o
> ld -r -o /var/lib/dkms/nvidia/384.69/build/nvidia-modeset/nv-modeset-interface.o /var/lib/dkms/nvidia/384.69/build/nvidia-modeset/nvidia-modeset-linux.o
>   LD [M]  /var/lib/dkms/nvidia/384.69/build/nvidia.o
>   LD [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-uvm.o
>   LD [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-modeset.o
>   LD [M]  /var/lib/dkms/nvidia/384.69/build/nvidia-drm.o
>   Building modules, stage 2.
>   MODPOST 4 modules
> FATAL: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol 'lockdep_init_map'
> make[2]: *** [scripts/Makefile.modpost:91: __modpost] Error 1
> make[1]: *** [Makefile:1520: modules] Error 2
> make[1]: Leaving directory '/usr/src/kernels/4.13.2-300.fc27.x86_64'
> make: *** [Makefile:81: modules] Error 2

**Comment by leigh123linux** [comment]
IMO this issue isn't possible to fix for dkms packaging as it requires changing the module licence, this makes the package not distributable.
It is possible to fix using akmod packaging as it distributed unmodified and patched locally.

**Comment by leigh123linux** [comment]
@scaronni This issue is invalid as the kernel has rawhide debugging enabled.

http://pkgs.fedoraproject.org/cgit/rpms/kernel.git/tree/kernel.spec?h=f27&id=a0ab8ce1ae0cc43929e064639db5df91229d83c4#n128

@tla2k12 add negative karma to

https://bodhi.fedoraproject.org/updates/FEDORA-2017-23dba9fb5d
