### ISSUE TITLE
dkms.nvidia download time out for 390.25 on Fedora 27

### ISSUE THREAD

**Issue by Brushtail-Highton** [negativo17/dkms-nvidia#7]
When issuing a sudo dnf upgrade on Fedora 27 the process always times out trying to download the 390.25 versions of dkms-nvidia and akmod-nvidia because the download speed drops to below 1000 b/sec, are the negativo17 nvidia repos down for an extended period of time? The following is an example of the messages I get:
[MIRROR] dkms-nvidia-390.25-1.fc27.x86_64.rpm: Curl error (28): Timeout was reached for https://negativo17.org/repos/nvidia/fedora-27/x86_64/dkms-nvidia-390.25-1.fc27.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
I have been getting this issue for the last 3 days, and, as a result of the time out none of the upgrade packages ever get installed as dnf terminates on these issues.
I tried the multimedia repository instead of the nvidia repository and I was able to download the akmod-nvidia package but not the dkms-nividia package, and I also now get the same issue with Blender 2.79.

**Comment by Brushtail-Highton** [comment]
By default dnf on Fedora 27 does 3 downloads in parallel, I have determined that if a download from another repository at the same time as a download from the negativo17 repositories, or there are multiple downloads from the negativo17 repositories in parallel the timeout occurs. I have temporarily worked around the issue by limiting the downloads by dnf to one at a time.

**Comment by LinuxPersonEC** [comment]
I know this issue is closed but this is happening whenever there are updates in this repo.
On Fedora 30 I always have to manually install updates. I always get these curl errors:
```
[MIRROR] nvidia-driver-cuda-libs-440.36-1.fc30.x86_64.rpm: Curl error (28): Timeout was reached for https://negativo17.org/repos/nvidia/fedora-30/x86_64/nvidia-driver-cuda-libs-440.36-1.fc30.x86_64.rpm [Operation timed out after 30211 milliseconds with 0 out of 0 bytes received]
[MIRROR] nvidia-kmod-common-440.36-1.fc30.noarch.rpm: Curl error (28): Timeout was reached for https://negativo17.org/repos/nvidia/fedora-30/x86_64/nvidia-kmod-common-440.36-1.fc30.noarch.rpm [Operation timed out after 30020 milliseconds with 0 out of 0 bytes received]
```

But if I run dnf install on each that fails, e.g., `dnf install https://negativo17.org/repos/nvidia/fedora-30/x86_64/nvidia-driver-cuda-libs-440.36-1.fc30.x86_64.rpm`, it works.

I made sure to disable `max_parallel_downloads` in `/etc/dnf/dnf.conf`. Is there another setting? I have `installonly_limit=3`.
