### ISSUE TITLE
RH 7 "yum update" breaks system when both kernel and dkms-nvidia are updated.

### ISSUE THREAD

**Issue by lamberss** [negativo17/dkms-nvidia#9]
The dkms-nvidia package only works properly if the latest kernel installed on the system is the same as the active kernel.  So, for example, if you run "yum update" (or just check the "Install updates" checkbox on power down) and both the kernel and the dkms-nvidia are updated, then the system will get a frown face with a logout button and not let me log in.  I have to boot into single user mode and do "yum reinstall dkms-nvidia" in order to fix the issue.

You run into a similar error if you install RH from scratch, then run "yum update" and install dkms-nvidia for the first time after running "yum update" but before rebooting.

I assume this error would also happen with CentOS 7, but I have not confirmed.

**Comment by scaronni** [comment]
Hello, it does not happen here. There is a similar behaviour when a dkms module and an updated kernel (including kernel-devel) are installed in the same transaction. This screws up the module status due to DKMS bugs.

Can you check if the behaviour you are describing is happening because of this?

**Comment by scaronni** [comment]
Just to be more clear, the tittle of this issue is correct, but what you are describing is just with active/non active kernels. What I (always) see is the issue happening when both a kernel-devel and a DKMS update are in the same yum transaction.

**Comment by lamberss** [comment]
All of my observances in the past have been issues with single yum transactions, with one exception.

On a fresh install of RH from DVD, if I do "yum update" then "yum install dkms-nvidia" as a separate transaction I still get the described behavior.  If I do a "yum update", then reboot, then "yum install dkms-nvidia" everything works fine.

Anyway, the primary annoyance is with the "yum update" not working without intervention.  But, it sounds like this is a DKMS shortcoming and not an issue with your specific package.

**Comment by scaronni** [comment]
Thanks for specifying. Yes, it's an issue with DKMS. Are you using the official kernel from the Red Hat main channel? You can use the binary module directly (`kmod-nvidia`).

**Comment by lamberss** [comment]
We have run into an issue in the past with other repositories providing kmod-nvidia where the repository providing kmod-nvidia would lag behind the red hat repository.  Most of the time things worked fine, but every now and then a "yum update" would update the kernel before the new kmod-nvidia was available and that would lead to problems.

How much lag is there normally between your repository and the red hat repository?

**Comment by scaronni** [comment]
Good point... I normally try to be on par with what is required (including small udpates intra minor relese, which rarely happen), but there can be delays with CentOS and I can't make the repository work with both Red Hat kernels and CentOS kernels which might be slightly offset. Making one work would break the other and most of the people are actually using CentOS.

I have access to a few Red Hat machines, most of the time I just hold back the kernel update for a few days when there are minor releases (7.3, 7.4, etc.) until CentOS catches up.

I guess that yeah, DKMS or akmods are the best choice. I will add akmods soon to the RHEL 7 repositories, now that akmods is in epel.

**Comment by lamberss** [comment]
Okay, thanks.

I think for now I will just disable the "epel-nvidia" repo on our systems so that "yum update" will always work.  Then, if we need to update to the latest version of the driver, we can run "yum update --enablerepo=epel-nvidia".

I will probably give the akmod packages a shot when they are available.

**Comment by Atticfire** [comment]
Just upgraded Fedora 28 to 29, using nvidia-driver 3:410.73-4.fc29
When installing dkms-nvidia 3:410.73-1.fc29 :- 

Installs and compiles correctly
Loads the nvidia library to memory correctly at that point systemctl isolate graphical will start Xorg
dkms status show nvdia loaded ONLY DURING THE INSTALL

But as the dkms-nvida script continues it cleans up all the compile work done

dkms build -m nvidia -v 410.73 -q || :
dkms install -m nvidia -v 410.73 -q --force || :
preuninstall scriptlet (using /bin/sh):
# Remove all versions from DKMS registry
dkms remove -m nvidia -v 410.73 -q --all || :

This then removes dkms-nvida library so reboots do no longer work
